server:
  port: 8089
spring:
  application:
    name: data-transfer
beta: 
  discovery:
    listener: true
    logPath: /dataxapp/nohup.out
    version: 1.0.1
    description: 数据同步程序
    environment: Public
    watch:
      watch: true
      time: 5000 #配置多少秒监控一次
    serverAddr: http://localhost:7055/risedata
  servers: rpc:127.0.0.1:7066